/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.AccountDirectory;

/**
 *
 * @author Lakshman
 */
public class AccountMngWorkAreaJPanel extends javax.swing.JPanel {
	
	public JPanel userProcessContainer;
	public AccountDirectory accountDirectory;

	/**
	 * Creates new form AccountMngWorkAreaJPanel
	 */
	public AccountMngWorkAreaJPanel(JPanel container, AccountDirectory accDir) {
		initComponents();
		userProcessContainer = container;
		accountDirectory = accDir;
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createBtn = new javax.swing.JButton();
        manageBtn = new javax.swing.JButton();

        createBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createBtn.setText("Create Account");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        manageBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        manageBtn.setText("Manage Account");
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(654, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(createBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageBtn)
                .addContainerGap(354, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
	// TODO add your handling code here:
	CreateAccountJPanel panel = new CreateAccountJPanel(userProcessContainer, accountDirectory);
	userProcessContainer.add("AccountMngWorkAreaJPanel",  panel);
	
	CardLayout layout = (CardLayout) userProcessContainer.getLayout();
	layout.next(userProcessContainer);
    }//GEN-LAST:event_createBtnActionPerformed

    private void manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBtnActionPerformed
	// TODO add your handling code here:
	ManageAccountsJPanel panel = new ManageAccountsJPanel(userProcessContainer, accountDirectory);
	userProcessContainer.add("AccountMngWorkAreaJPanel",  panel);
	
	CardLayout layout = (CardLayout) userProcessContainer.getLayout();
	layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JButton manageBtn;
    // End of variables declaration//GEN-END:variables
}
