/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account;
import model.AccountDirectory;

/**
 *
 * @author Lakshman
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

	public JPanel userProcessContainer;
	public AccountDirectory accountDirectory;
	
	/**
	 * Creates new form CreateAccountJPanel
	 */
	public CreateAccountJPanel(JPanel container, AccountDirectory accDir) {
		initComponents();
		userProcessContainer = container;
		accountDirectory = accDir;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        routingNumberLabel = new javax.swing.JLabel();
        accountNumberLabel = new javax.swing.JLabel();
        bankNameLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        routingNumber = new javax.swing.JTextField();
        accountNumber = new javax.swing.JTextField();
        bankName = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        createAccBtn = new javax.swing.JButton();

        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backBtn.setText("<<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title.setText("Create Account");

        routingNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        routingNumberLabel.setText("Routing Number");

        accountNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountNumberLabel.setText("Account Number");

        bankNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bankNameLabel.setText("Bank Name");

        balanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        balanceLabel.setText("Balance");

        createAccBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createAccBtn.setText("Create Account");
        createAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backBtn)
                        .addGap(261, 261, 261)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(routingNumberLabel)
                            .addComponent(accountNumberLabel)
                            .addComponent(bankNameLabel)
                            .addComponent(balanceLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(bankName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(accountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(routingNumber)
                            .addComponent(createAccBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addComponent(backBtn))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routingNumberLabel)
                    .addComponent(routingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumberLabel)
                    .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameLabel)
                    .addComponent(bankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLabel)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(createAccBtn)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
	// TODO add your handling code here:
	userProcessContainer.remove(this);
	CardLayout layout = (CardLayout) userProcessContainer.getLayout();
	layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtnActionPerformed
	// TODO add your handling code here:
	int bal;
	String routeNumber = routingNumber.getText();
	String accNumber = accountNumber.getText();
	String bName = bankName.getText();
	
	if(routeNumber.isBlank() || accNumber.isBlank() || bName.isBlank()) {
		JOptionPane.showMessageDialog(this, "All fields are mandatory", "Field Validation",  JOptionPane.ERROR_MESSAGE);
		return;
	}
	
	try {
		bal = Integer.parseInt(balance.getText());
	} catch (Exception e) {
		JOptionPane.showMessageDialog(null, "Please check the balance input", "Warning", JOptionPane.WARNING_MESSAGE);
		return;
	}
	
	Account acc = accountDirectory.addAccount();
	acc.setAccountNumber(accNumber);
	acc.setBalance(bal);
	acc.setBankName(bName);
	acc.setRoutingNumber(routeNumber);
	
	JOptionPane.showMessageDialog(this, "Account successfully created", "Information",  JOptionPane.INFORMATION_MESSAGE);
	
	routingNumber.setText("");
	accountNumber.setText("");
	bankName.setText("");
	balance.setText("");
    }//GEN-LAST:event_createAccBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumber;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField balance;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JTextField bankName;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JButton createAccBtn;
    private javax.swing.JTextField routingNumber;
    private javax.swing.JLabel routingNumberLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
