/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account;
import model.AccountDirectory;

/**
 *
 * @author Lakshman
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

	public JPanel userProcessContainer;
	public AccountDirectory accountDirectory;
	public Account account;
	
	/**
	 * Creates new form ViewAccountJPanel
	 */
	public ViewAccountJPanel(JPanel container, AccountDirectory accDir, Account acc) {
		initComponents();
		userProcessContainer = container;
		accountDirectory = accDir;
		account = acc;
		
		setTextFields();
		setReadOnlyMode();
	}
	
	public void setTextFields() {
		accountNumber.setText(account.getAccountNumber());
		routingNumber.setText(account.getRoutingNumber());
		bankName.setText(account.getBankName());
	}
	
	public void setReadOnlyMode() {
		accountNumber.setEnabled(false);
		routingNumber.setEnabled(false);
		bankName.setEnabled(false);
		
		saveBtn.setEnabled(false);
		updateBtn.setEnabled(true);
	}
	
	public void setEditMode() {
		accountNumber.setEnabled(true);
		routingNumber.setEnabled(true);
		bankName.setEnabled(true);

		saveBtn.setEnabled(true);
		updateBtn.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bankNameLabel = new javax.swing.JLabel();
        routingNumber = new javax.swing.JTextField();
        accountNumber = new javax.swing.JTextField();
        bankName = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        routingNumberLabel = new javax.swing.JLabel();
        accountNumberLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();

        bankNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bankNameLabel.setText("Bank Name");

        updateBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backBtn.setText("<<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title.setText("View Account");

        routingNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        routingNumberLabel.setText("Routing Number");

        accountNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountNumberLabel.setText("Account Number");

        saveBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backBtn)
                        .addGap(261, 261, 261)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(routingNumberLabel)
                            .addComponent(accountNumberLabel)
                            .addComponent(bankNameLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bankName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(accountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(routingNumber)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addComponent(backBtn))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routingNumberLabel)
                    .addComponent(routingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumberLabel)
                    .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameLabel)
                    .addComponent(bankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(saveBtn))
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
	// TODO add your handling code here:
	userProcessContainer.remove(this);
	
	Component[] panelStack = userProcessContainer.getComponents();
	JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
	ManageAccountsJPanel manageAccountsJPanel = (ManageAccountsJPanel) lastPanel;
	manageAccountsJPanel.populateTable();
	
	CardLayout layout = (CardLayout) userProcessContainer.getLayout();
	layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
	// TODO add your handling code here:
	setEditMode();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
	// TODO add your handling code here:
	String routeNumber = routingNumber.getText();
	String accNumber = accountNumber.getText();
	String bName = bankName.getText();
	
	if(routeNumber.isBlank() || accNumber.isBlank() || bName.isBlank()) {
		JOptionPane.showMessageDialog(this, "All fields are mandatory", "Field Validation",  JOptionPane.ERROR_MESSAGE);
		return;
	}
	
	account.setAccountNumber(accNumber);
	account.setRoutingNumber(routeNumber);
	account.setBankName(bName);
	
	JOptionPane.showMessageDialog(this, "Account successfully updated", "Information",  JOptionPane.INFORMATION_MESSAGE);
	
	setReadOnlyMode();
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumber;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bankName;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JTextField routingNumber;
    private javax.swing.JLabel routingNumberLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel title;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
